
package gestionviajes;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rubensegura
 */
public class Principal extends javax.swing.JFrame {
    
    // OBJETOS DE OTRAS VENTANAS
    Clientes gestionClientes = new Clientes(this, rootPaneCheckingEnabled);
    Paquetes gestionPaquetes = new Paquetes(this, rootPaneCheckingEnabled);
    Ventas gestionVentas = new Ventas(this, rootPaneCheckingEnabled);
    VentanaInformeCondicional ventanaCondicional = new VentanaInformeCondicional(this, rootPaneCheckingEnabled);

    /**
     * Creates new form principal
     */
    public Principal() {
        try{
            Splash sp=new Splash("/img/logo-cargando.png",new JFrame(), 5000);
            Thread.sleep(500);
        }catch ( InterruptedException e) {
            System.out.println("Error al cargar img splash");
        }
        initComponents();
        //icono de la app
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono-app.png")));
        //Base de Datos
        con = new BaseDeDatos("viajes.db");
        con.ConectaBD();
        try {
            con.consulta.executeUpdate("PRAGMA foreign_keys=on");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        } finally {
            System.out.println("Ejecuto los pragma de foreign key correctamente...");
        }
        tooltips();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuEmergente = new javax.swing.JPopupMenu();
        popupEditar = new javax.swing.JMenuItem();
        btnMain_clientes = new javax.swing.JButton();
        btnMain_paquetes = new javax.swing.JButton();
        btnMain_ventas = new javax.swing.JButton();
        logoMain = new javax.swing.JLabel();
        labelMain_titulo = new javax.swing.JLabel();
        MenuBarMain = new javax.swing.JMenuBar();
        btnMain_archivo = new javax.swing.JMenu();
        btnMenuBarMainAyuda = new javax.swing.JMenuItem();
        btnMenuBarMainAcercaDe = new javax.swing.JMenuItem();
        btnMenuBarMainReiniciaBD = new javax.swing.JMenuItem();
        btnMenuBarMainSalir = new javax.swing.JMenuItem();
        btnMainInformes = new javax.swing.JMenu();
        btnInformeCliente = new javax.swing.JMenuItem();
        btnInformePaquetes = new javax.swing.JMenuItem();
        btnInformeVentas = new javax.swing.JMenuItem();
        btnVentanaInformeCondicional = new javax.swing.JMenuItem();

        popupEditar.setText("jMenuItem1");
        popupEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupEditarActionPerformed(evt);
            }
        });
        jPopupMenuEmergente.add(popupEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de viajes");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        btnMain_clientes.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnMain_clientes.setMnemonic('C');
        btnMain_clientes.setText("Clientes");
        btnMain_clientes.setToolTipText("");
        btnMain_clientes.setPreferredSize(new java.awt.Dimension(170, 80));
        btnMain_clientes.setSelected(true);
        btnMain_clientes.setSize(new java.awt.Dimension(170, 80));
        btnMain_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMain_clientesActionPerformed(evt);
            }
        });

        btnMain_paquetes.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnMain_paquetes.setMnemonic('P');
        btnMain_paquetes.setText("Paquetes");
        btnMain_paquetes.setToolTipText("");
        btnMain_paquetes.setPreferredSize(new java.awt.Dimension(170, 80));
        btnMain_paquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMain_paquetesActionPerformed(evt);
            }
        });

        btnMain_ventas.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnMain_ventas.setMnemonic('V');
        btnMain_ventas.setText("Ventas");
        btnMain_ventas.setToolTipText("");
        btnMain_ventas.setPreferredSize(new java.awt.Dimension(170, 80));
        btnMain_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMain_ventasActionPerformed(evt);
            }
        });

        logoMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logoMain.setToolTipText("Logo de gestión de viajes");

        labelMain_titulo.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        labelMain_titulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMain_titulo.setText("Gestión de viajes");

        btnMain_archivo.setMnemonic('A');
        btnMain_archivo.setText("Archivo");

        btnMenuBarMainAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuBarMainAyuda.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMenuBarMainAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda-icon.png"))); // NOI18N
        btnMenuBarMainAyuda.setText("Manual de usuario");
        btnMenuBarMainAyuda.setToolTipText("");
        btnMenuBarMainAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBarMainAyudaActionPerformed(evt);
            }
        });
        btnMain_archivo.add(btnMenuBarMainAyuda);

        btnMenuBarMainAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuBarMainAcercaDe.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMenuBarMainAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acerca-de.png"))); // NOI18N
        btnMenuBarMainAcercaDe.setText("Acerca De");
        btnMenuBarMainAcercaDe.setToolTipText("");
        btnMenuBarMainAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBarMainAcercaDeActionPerformed(evt);
            }
        });
        btnMain_archivo.add(btnMenuBarMainAcercaDe);

        btnMenuBarMainReiniciaBD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuBarMainReiniciaBD.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMenuBarMainReiniciaBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reinicia-bd.png"))); // NOI18N
        btnMenuBarMainReiniciaBD.setText("Reiniciar BD");
        btnMenuBarMainReiniciaBD.setToolTipText("");
        btnMenuBarMainReiniciaBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBarMainReiniciaBDActionPerformed(evt);
            }
        });
        btnMain_archivo.add(btnMenuBarMainReiniciaBD);

        btnMenuBarMainSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnMenuBarMainSalir.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnMenuBarMainSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnMenuBarMainSalir.setText("Salir de la aplicación");
        btnMenuBarMainSalir.setToolTipText("");
        btnMenuBarMainSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBarMainSalirActionPerformed(evt);
            }
        });
        btnMain_archivo.add(btnMenuBarMainSalir);

        MenuBarMain.add(btnMain_archivo);

        btnMainInformes.setText("Informes");

        btnInformeCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        btnInformeCliente.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnInformeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informe.png"))); // NOI18N
        btnInformeCliente.setText("Informe de clientes");
        btnInformeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeClienteActionPerformed(evt);
            }
        });
        btnMainInformes.add(btnInformeCliente);

        btnInformePaquetes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        btnInformePaquetes.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnInformePaquetes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informe.png"))); // NOI18N
        btnInformePaquetes.setText("Informe de paquetes");
        btnInformePaquetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformePaquetesActionPerformed(evt);
            }
        });
        btnMainInformes.add(btnInformePaquetes);

        btnInformeVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        btnInformeVentas.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnInformeVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informe.png"))); // NOI18N
        btnInformeVentas.setText("Informe de ventas");
        btnInformeVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeVentasActionPerformed(evt);
            }
        });
        btnMainInformes.add(btnInformeVentas);

        btnVentanaInformeCondicional.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        btnVentanaInformeCondicional.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        btnVentanaInformeCondicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informe.png"))); // NOI18N
        btnVentanaInformeCondicional.setText("Informe condicional");
        btnVentanaInformeCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaInformeCondicionalActionPerformed(evt);
            }
        });
        btnMainInformes.add(btnVentanaInformeCondicional);

        MenuBarMain.add(btnMainInformes);

        setJMenuBar(MenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelMain_titulo)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMain_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMain_paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMain_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(logoMain)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelMain_titulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMain_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnMain_paquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnMain_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMain_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMain_clientesActionPerformed
        System.out.println("Abro ventana de gestión de CLIENTES");
        gestionClientes.darConexionAbierta(con);
        gestionClientes.listarClientes("","",false);
        gestionClientes.desactivarBotones();
        gestionClientes.setVisible(true);
    }//GEN-LAST:event_btnMain_clientesActionPerformed

    private void btnMain_paquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMain_paquetesActionPerformed
        System.out.println("Abro ventana de gestión de PAQUETES");
        gestionPaquetes.darConexionAbierta(con);
        gestionPaquetes.listarPaquetes("","",false);
        gestionPaquetes.desactivarBotones();
        gestionPaquetes.setVisible(true);
    }//GEN-LAST:event_btnMain_paquetesActionPerformed

    private void btnMain_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMain_ventasActionPerformed
        System.out.println("Abro ventana de gestión de VENTAS");
        gestionVentas.darConexionAbierta(con);
        gestionVentas.listarVentas("", "",false);
        gestionVentas.desactivarBotones();
        gestionVentas.setVisible(true);
    }//GEN-LAST:event_btnMain_ventasActionPerformed

    private void btnMenuBarMainSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBarMainSalirActionPerformed
        System.out.println("Cierro la aplicación");
        con.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_btnMenuBarMainSalirActionPerformed

    private void btnMenuBarMainReiniciaBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBarMainReiniciaBDActionPerformed
        System.out.println("Reinicio la base de datos");
        this.con.reiniciaBBDD();
        JOptionPane.showMessageDialog(null, "Se ha reiniciado la BD correctamente", "Reinicio de BD", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMenuBarMainReiniciaBDActionPerformed

    private void btnMenuBarMainAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBarMainAcercaDeActionPerformed
        System.out.println("Muestro información 'Acerca de' ");
        JOptionPane.showMessageDialog(null, "Gestión de viajes App \nVersión 1.1 \nDesarrollo por Rubén Segura Romo","Acerca de", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMenuBarMainAcercaDeActionPerformed

    private void btnMenuBarMainAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBarMainAyudaActionPerformed
        System.out.println("Abro el manual de usuario");
            File file = new File("manual.pdf");
            if(!Desktop.isDesktopSupported()){
                JOptionPane.showMessageDialog(null, "Este sistema operativo no puede abrir el manual de usuario","Error al abrir manual", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Desktop desktop = Desktop.getDesktop();
            if(file.exists()) try {
                desktop.open(file);
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            else{
                JOptionPane.showMessageDialog(null, "El manual de usuario no se ha encontrado en el sistema","Manual de usuario no disponible", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnMenuBarMainAyudaActionPerformed

    private void tooltips() {
        btnMain_clientes.setToolTipText("<html>Ir a <b>gestión clientes</b>\n<br>Atajo <b>ALT + C</b></html>");
        btnMain_paquetes.setToolTipText("<html>Ir a <b>gestión paquetes</b>\n<br>Atajo <b>ALT + P</b></html>");
        btnMain_ventas.setToolTipText("<html>Ir a <b>gestión ventas</b>\n<br>Atajo <b>ALT + V</b></html>");
        btnMain_archivo.setMnemonic('A');
        btnMain_archivo.setToolTipText("<html>Abre menú <b>archivo</b>\n<br>Atajo <b>ALT + A</b></html>");
        btnMenuBarMainAcercaDe.setToolTipText("<html>Abre ventana con <b>información</b> sobre la aplicación\n<br>Atajo <b>Ctrl + A</b></html>");
        btnMenuBarMainAyuda.setToolTipText("<html>Abre el <b>manual de usuario</b> de la aplicación\n<br>Atajo <b>Ctrl + M</b></html>");
        btnMenuBarMainReiniciaBD.setToolTipText("<html>Reinicia la base de datos\n<br>Atajo <b>Ctrl + R</b></html>");
        btnMenuBarMainSalir.setToolTipText("<html>Cierra la aplicación\n<br>Atajo <b>Ctrl + S</b></html>");
        btnMainInformes.setMnemonic('I');
        btnMainInformes.setToolTipText("<html>Abre el <b>menú de informes</b></html>");
        btnInformeCliente.setToolTipText("<html>Genera un <b>informe sobre clientes.</b>\n<br>Atajo <b>Mayus. + C</b></html>");
        btnInformePaquetes.setToolTipText("<html>Genera un <b>informe sobre paquetes con gráficos comparativos.</b>\n<br>Atajo <b>Mayus. + P</b></html>");
        btnInformeVentas.setToolTipText("<html>Genera un <b>informe sobre ventas</b>\n<br><br>Atajo <b>Mayus. + V</b></html>");
        btnVentanaInformeCondicional.setToolTipText("<html>Abre una ventana en la que puedes generar un <b>informe sobre ventas condicionado por destino de un paquete</b>\n<br><br>Atajo <b>Mayus. + I</b></html>");
    }
    
    private void popupEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupEditarActionPerformed
        System.out.println("Muestro popup Menú principal");
    }//GEN-LAST:event_popupEditarActionPerformed

    private void btnInformeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeClienteActionPerformed
        System.out.println("Genero informe de clientes en pdf");
        String informe = "/informes/clientesActuales.jrxml";
        generarInforme("",informe);
    }//GEN-LAST:event_btnInformeClienteActionPerformed

    private void btnInformePaquetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformePaquetesActionPerformed
        System.out.println("Genero informe de paquetes y comparativa de precios en pdf");
        String informe = "/informes/paquetesPorPrecio.jrxml";
        generarInforme("", informe);
    }//GEN-LAST:event_btnInformePaquetesActionPerformed

    private void btnInformeVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeVentasActionPerformed
        System.out.println("Genero informe de ventas en pdf");
        String informe = "/informes/ventasCompuesta.jrxml";
        generarInforme("", informe);
    }//GEN-LAST:event_btnInformeVentasActionPerformed

    private void btnVentanaInformeCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaInformeCondicionalActionPerformed
        System.out.println("Abro ventana informe ventas con condicional");
        ventanaCondicional.darConexionAbierta(con);
        ventanaCondicional.preparaVentana();
        ventanaCondicional.setVisible(true);
    }//GEN-LAST:event_btnVentanaInformeCondicionalActionPerformed
    
    private void generarInforme(String tipo, String nombre) {
        Connection conexionBaseDatos = con.dameConexion();
        InputStream jasperStream = (InputStream) getClass().getResourceAsStream(nombre);
        Map parametros = new HashMap();
        parametros.put("CONDICION", tipo);
        try {
            JasperReport informeCompilado = JasperCompileManager.compileReport(jasperStream);
            JasperPrint informeRellenado = JasperFillManager.fillReport(informeCompilado, parametros,conexionBaseDatos);
            JasperViewer.viewReport(informeRellenado);
        } catch(JRException e) {
            JOptionPane.showMessageDialog(null, "Error al generar el informe"+e.getMessage(),"Atención",JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
        
    }

    // Var para la conexion con la BD
    private BaseDeDatos con;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBarMain;
    private javax.swing.JMenuItem btnInformeCliente;
    private javax.swing.JMenuItem btnInformePaquetes;
    private javax.swing.JMenuItem btnInformeVentas;
    private javax.swing.JMenu btnMainInformes;
    private javax.swing.JMenu btnMain_archivo;
    private javax.swing.JButton btnMain_clientes;
    private javax.swing.JButton btnMain_paquetes;
    private javax.swing.JButton btnMain_ventas;
    private javax.swing.JMenuItem btnMenuBarMainAcercaDe;
    private javax.swing.JMenuItem btnMenuBarMainAyuda;
    private javax.swing.JMenuItem btnMenuBarMainReiniciaBD;
    private javax.swing.JMenuItem btnMenuBarMainSalir;
    private javax.swing.JMenuItem btnVentanaInformeCondicional;
    private javax.swing.JPopupMenu jPopupMenuEmergente;
    private javax.swing.JLabel labelMain_titulo;
    private javax.swing.JLabel logoMain;
    private javax.swing.JMenuItem popupEditar;
    // End of variables declaration//GEN-END:variables
}
